adding unit tests for sdk types
tago-io/tcore pull request #23
Opened 2022-08-11 17:58 UTC by cercena

2022-09-01 16:32 UTC, FabianoEger reviewed
@cercena please, resolve conflicts

2022-09-01 17:16 UTC, matheuslbenachio requested changes
Fix requested changes so I can merge

2022-09-01 17:16 UTC, matheuslbenachio commented on packages/tcore-sdk/src/Types/Account/Account.types.test.ts
> +        "Invalid enum value. Expected 'id' | 'name' | 'username' | 'password' | 'password_hint' | 'created_at'"
Don't use all the values here, otherwise if we change the `zAccountListQuery` we have to change the tests as well

2022-09-01 17:16 UTC, matheuslbenachio commented on packages/tcore-sdk/src/Types/Account/Account.types.test.ts
> +      expect(e.fieldErrors.permission[0]).toBe("Invalid enum value. Expected 'full' | 'read' | 'write'");
Don't use all the values here, otherwise if we change the zAccountTokenCreate we have to change the tests as well

2022-09-01 17:16 UTC, matheuslbenachio commented on packages/tcore-sdk/src/Types/Hardware/Hardware.types.test.ts
> +        "Invalid enum value. Expected 'windows' | 'mac' | 'linux' | 'raspberry-pi' | 'other'"
Don't use all the values here, otherwise if we change the zod object we have to change the tests as well

2022-09-01 17:16 UTC, matheuslbenachio commented on packages/tcore-sdk/src/Types/Helpers/parseRelativeDate.test.ts
> +  test("simple parse", () => {
remove useless test

2022-09-01 17:16 UTC, matheuslbenachio commented on packages/tcore-sdk/src/Types/Helpers/preprocessBoolean.test.ts
> +    expect(process).toBeFalsy;
This test is wrong, `toBeFalsy` is not being called

2022-09-01 17:16 UTC, matheuslbenachio commented on packages/tcore-sdk/src/Types/Helpers/preprocessObject.test.ts
> +    expect(typeof process).toBe("object" || "null");
This test is wrong, it's always going to compare with object, there is no need to do `"object" || "null"`

2022-09-01 17:16 UTC, matheuslbenachio commented on packages/tcore-sdk/src/Types/Helpers/refineOrderBy.test.ts
> +    expect(process).toBeTruthy;
`toBeTruthy` is not being invoked

2022-09-01 17:16 UTC, matheuslbenachio commented on packages/tcore-sdk/src/Types/Helpers/removeNullValues.test.ts
> +    expect(process).toBeInstanceOf(Object);
I don't understand this test. You're only checking if the result is an instance of `Object`? you should check if it removed the null value, not if it's an instance of Object

2022-09-01 17:16 UTC, matheuslbenachio commented on packages/tcore-sdk/src/Types/Helpers/createQueryOrderBy.test.ts
> +    const data = createQueryOrderBy(query as any);
I'm not sure I understand this test, what are you trying to achieve?

2022-09-01 17:16 UTC, matheuslbenachio commented on packages/tcore-sdk/src/Types/Helpers/removeNullValues.test.ts
> +    expect(process).toBeInstanceOf(Object);
Same thing as above here

2022-09-01 17:16 UTC, matheuslbenachio commented on packages/tcore-sdk/src/Types/LiveInspector/LiveInspector.types.test.ts
> +    expect(parsed.content).toBeUndefined;
`toBeUndefined` is not being invoked

2022-09-01 17:16 UTC, matheuslbenachio commented on packages/tcore-sdk/src/Types/LiveInspector/LiveInspector.types.test.ts
> +    expect(parsed.title).toEqual("title");
You should probably use expect to see if the other fields are there as well

2022-09-01 17:16 UTC, matheuslbenachio commented on packages/tcore-sdk/src/Types/LiveInspector/LiveInspector.types.test.ts
> +    expect(parsed.title).toEqual("title");
You should probably use expect to see if the other fields are there as well

2022-09-01 17:16 UTC, matheuslbenachio commented on packages/tcore-sdk/src/Types/Log/Log.types.test.ts
> +    expect(parsed.message).toEqual("message");
You should probably use expect to see if the other fields are there as well

2022-09-01 17:16 UTC, matheuslbenachio commented on packages/tcore-sdk/src/Types/Log/Log.types.test.ts
> +    expect(parsed[0].message).toEqual("message");
You should probably use expect to see if the other fields are there as well

2022-09-01 17:16 UTC, matheuslbenachio commented on packages/tcore-sdk/src/Types/Plugin/Plugin.types.test.ts
> +  test("invalid id", () => {
Also add a test with it working

2022-09-01 17:16 UTC, matheuslbenachio commented on packages/tcore-sdk/src/Types/Plugin/Plugin.types.test.ts
> +        "Invalid enum value. Expected 'action-trigger' | 'action-type' | 'database' | 'decoder' | 'encoder' | 'filesystem' | 'hook' | 'navbar-button' | 'page' | 'service' | 'sidebar-button' | 'sideba
Don't add all the values in test, it's going to be difficult to change it later on

2022-09-01 17:16 UTC, matheuslbenachio commented on packages/tcore-sdk/src/Types/Plugin/Plugin.types.test.ts
> +    expect(parsed.domain).toBeUndefined;
`toBeUndefined` not being invoked

2022-09-01 17:16 UTC, matheuslbenachio commented on packages/tcore-sdk/src/Types/Plugin/Plugin.types.test.ts
> +    expect(parsed.start).toBeUndefined;
`toBeUndefined` not being invoked

2022-09-01 17:16 UTC, matheuslbenachio commented on packages/tcore-sdk/src/Types/Plugin/Plugin.types.test.ts
> +      expect(e.formErrors[0]).toBe(
Don't add all the values in test, it's going to be difficult to change it later on

2022-09-01 17:16 UTC, matheuslbenachio commented on packages/tcore-sdk/src/Types/Plugin/Plugin.types.test.ts
> +    expect(parsed.description).toBeUndefined;
`toBeUndefined` not being invoked

2022-09-01 17:16 UTC, matheuslbenachio commented on packages/tcore-sdk/src/Types/Plugin/Plugin.types.test.ts
> +      expect(e.fieldErrors.types).toStrictEqual([
Don't add all the values in test, it's going to be difficult to change it later on

2022-09-01 17:16 UTC, matheuslbenachio commented on packages/tcore-sdk/src/Types/Plugin/Plugin.types.test.ts
> +        "Invalid enum value. Expected 'idle' | 'stopping' | 'starting' | 'started' | 'stopped'",
Don't add all the values in test, it's going to be difficult to change it later on

2022-09-01 17:16 UTC, matheuslbenachio commented on packages/tcore-sdk/src/Types/Settings/Settings.types.test.ts
> +    expect(parsed.version).toBeUndefined;
`toBeUndefined` not being invoked

2022-09-01 17:16 UTC, matheuslbenachio commented on packages/tcore-sdk/src/Types/Settings/Settings.types.test.ts
> +    expect(parsed.plugin_folder).toBeUndefined;
`toBeUndefined` not being invoked

2022-09-01 17:16 UTC, matheuslbenachio commented on packages/tcore-sdk/src/Types/Settings/Settings.types.test.ts
> +    expect(parsed.port_disabled).toBeTruthy;
`toBeTruthy` not being invoked

2022-09-01 17:16 UTC, matheuslbenachio commented on packages/tcore-sdk/src/Types/Statistic/Statistic.types.test.ts
> +    expect(parsed.input).toBeUndefined;
`toBeUndefined` not being invoked

2022-09-01 17:16 UTC, matheuslbenachio commented on packages/tcore-sdk/src/Types/Summary/Summary.types.test.ts
> +      expect(e.fieldErrors.analysis[0]).toBe("Required");
Check if the other ones are required as well

2022-09-01 17:16 UTC, matheuslbenachio commented on packages/tcore-sdk/src/Types/Tag/Tag.types.test.ts
> +    expect(parsed.key).toEqual("key");
Check the value as well

2022-09-01 17:27 UTC, FabianoEger commented on packages/tcore-sdk/src/Types/Account/Account.types.test.ts
> +        "Invalid enum value. Expected 'id' | 'name' | 'username' | 'password' | 'password_hint' | 'created_at'"
@cercena use startsWith('Invalid enum value....);

2022-09-23 13:50 UTC, matheuslbenachio requested changes

2022-09-23 13:50 UTC, matheuslbenachio commented on packages/tcore-sdk/src/Types/Account/Account.types.test.ts
> +    expect(parsed.fields).toBeNull;
This doesn't make sense, this function is not being called. Please review everything like this and then i'll check the tests.

2022-10-12 13:22 UTC, merged