TCORE-228 - Refactor plugin store and local
tago-io/tcore pull request #50
Opened 2024-10-08 17:35 UTC by bgelatti

2024-10-09 21:03 UTC, vitorfdl requested changes

2024-10-09 21:03 UTC, vitorfdl commented on packages/tcore-api/src/Plugins/Plugin/Plugin.ts
> +  }
Seems to be missing error handling

2024-10-09 21:03 UTC, vitorfdl commented on packages/tcore-api/src/Services/Plugins.ts
> +
prefer to use if for edge-cases instead of happy path.

Example:

```
if (!getPackage) {
continue;
}
```

2024-10-09 21:03 UTC, vitorfdl commented on packages/tcore-console/src/Components/Sidebar/PluginButton/PluginButton.tsx
> +            <span>Remove Plugin</span>
I'm confused on why still have a Remove button. Can you explain on the requirements? I was expecting to not have Remove/Uninstall buttons anymore.

2024-10-10 16:36 UTC, bgelatti commented on packages/tcore-api/src/Plugins/Plugin/Plugin.ts
> +  }
done

2024-10-10 16:38 UTC, bgelatti commented on packages/tcore-api/src/Services/Plugins.ts
> +
done

2024-10-10 16:41 UTC, bgelatti commented on packages/tcore-console/src/Components/Sidebar/PluginButton/PluginButton.tsx
> +            <span>Remove Plugin</span>
done

2024-10-15 15:51 UTC, merged